### ISSUE TITLE
Starte BeerJS?

### ISSUE THREAD

**Issue by mikaelbr** [BartJS/beerjs#1]
La oss få dette igang!

cc @ev1stensberg

**Comment by mikaelbr** [comment]
Da ser det ut til at du skal ha tilgang her, @ev1stensberg ? 🍰 🎉

**Comment by evenstensberg** [comment]
Yes, ordnet seg nå! :v: :pray:

**Comment by mikaelbr** [comment]
README-en ser veldig bra ut! Kan og muligens lenke til BartJS' egen Code of Conduct som er opprettet her: https://github.com/BartJS/organisering/blob/master/CodeOfConduct.md

**Comment by evenstensberg** [comment]
Done!
