### ISSUE TITLE
Avslutte BeerJS

### ISSUE THREAD

**Issue by evenstensberg** [BartJS/beerjs#3]
Har vært like tilbakemeldinger om BeerJS i det siste. Er det fortsatt interesse? @mikaelbr 
Om ikke, så vil dette repoet/BeerJS bli stengt i løpet av helga.

**Comment by mikaelbr** [comment]
Det har vært lite respons ettersom jeg har hatt veldig mye å gjøre. Vi hadde en Meetup på onsdag, og det gikk ganske greit. Ikke stor interesse for å samles etter, men det betyr ikke at det ikke ville vært interesse for å gjøre det en annen dag.

Det er et par planer jeg har som jeg må komme meg rundt å få gjøre: Skrive en post om filosofien rundt BartJS og noen ord om hva vi ønsker ut av det og hva slags plattform det skal være.

Men for BeerJS' del ser jeg ikke helt hvorfor du skulle måtte stenge repoet? Hva er det du mener mangler av meg som gjør at du vil gjøre det? Er BeerJS det samme som din ambisjon om mini-konferanse (#2)? Eller er det adskilte konsepter og mål?

Hva tenker du er veien fremover?

**Comment by evenstensberg** [comment]
Har generelt vært liten respons fra din side, og fikk inntrykk av at du hadde skiftet mening. BeerJS og #2 er to forskjellige ting, og jeg synes BartJS burde ta seg av dette, om det blir noe, så ikke BeerJS går inn på event organizing når det skal være en ren meetup uten den slags. 

Det er jo også grunnen til at jeg skrev opp dette, siden jeg ikke har fått respons per mail eller her. Jeg forslår at vi utsetter dette en mnd, kanskje to, også ser vi hvordan det ser ut når den tid kommer. Hva synes du?

**Comment by mikaelbr** [comment]
> Har generelt vært liten respons fra din side, og fikk inntrykk av at du hadde skiftet mening.

Nei, bare mye å gjøre og kjegler som sjongleres. Men for min del er det ikke så veldig mye som trengs å gjøres her. Håpet mitt var at mye av dette kunne planlegges og gjennomføres uten at jeg måtte være for mye involvert og balansere flere ting. Men jeg tenker vi bare finner en dag som vi ser for oss kan fungere, setter opp en event på Meetup.com og sender ut mail med informasjonen. Så ser vi an hvor stor interesse det er og reserverer bord en plass som passer.

Hva er det du tenker trengs for å gjennomføre dette? Såvidt jeg ser består det kun av 3 komponenter:
1. Arrangement (en event på Meetup.com)
2. Folk
3. Et sted
   (4. gode diskusjoner)

**Comment by evenstensberg** [comment]
Mulig at du sjekker rundt ang hvor stor pågang det er? Evnt noen som har lyst å co-organize? Jeg flytter i sommer, og kan ikke delta på alle arrangementer, dessverre.

**Comment by mikaelbr** [comment]
Tror du ikke pågang viser seg selv om man oppretter eventen?

**Comment by evenstensberg** [comment]
Jo det kan være.

**Comment by mikaelbr** [comment]
Vi kan finne en dag som passer bra så kan vi sette opp en Meetup-event på det og sende ut e-post med informasjon?

**Comment by evenstensberg** [comment]
Ikke på meetup.com ?

**Comment by mikaelbr** [comment]
Jo, en Meetup-event på meetup.com
