### ISSUE TITLE
Beerjs #1?

### ISSUE THREAD

**Issue by eiriksm** [BartJS/beerjs#4]
Hello.

La oss bare sette en dato, finne et sted, annonsere BeerJS, og se om det kommer noen :) 🍻 
- [x] Sette en dato
- [x] Finne et sted
- [x] Annonsere en BeerJS
- [x] Se om det kommer noen

Så, for å komme med masse konstruktivt på en gang. Her er et forslag til en dato: torsdag 4. august.

Her er også et forslag til sted: Taps, på Bakklandet, siden det er min personlige favoritt.

Kjør debatt!

**Comment by evenstensberg** [comment]
Mulig at jeg har diskutert dette internt med Mikael, men jeg har ikke mulighet til å være med aktivt på BeerJS, men kan stå for å arrangere dette. Tror dette egentlig kunne funke av seg selv, så lenge alle oppfører seg slik de alltid gjør, og at det er et strukturert program på forhånd. Den er dårlig for min del, siden er drar til SF den dagen, men er gira på å få andre med denne dagen! Eller hva sier du @mikaelbr ?

**Comment by mikaelbr** [comment]
Syns 4. august høres bra ut! Det er samtidig som bryggerifestivalen, men mesteparten av arrangementet skjer vel kanskje på lørdag og fredag?

Taps funker bra, tror jeg. Det er godt øl og rolig atmosfære. Alternativt er Work-Work som ikke nødvendigvis har utmerket øl, men er kanskje mer appellerende for mainstreamen og for de som ikke er så interessert i øl. Go for forslaget sier da jeg.

**Comment by eiriksm** [comment]
Er jo ikke så farlig at det er godt øl, strengt tatt. Selv om jeg personlig er en fan ;)

Skal vi bare kjøre ut en meetup event? Eller er det reservert bartjs "vanlige" meetups?

**Comment by evenstensberg** [comment]
Utifra det jeg og Mikael har utvekslet av informasjon, så kjører vi vell ut en MeetUp event :)

**Comment by mikaelbr** [comment]
Ja, kjør på med en meetup-event, så når vi alle medlemmer.

**Comment by evenstensberg** [comment]
Blir det at jeg eller du lager da @mikaelbr ? Vil benytte sjangsen til å takke @eiriksm for bra intiativ, takker så mye for tro til konseptet!

**Comment by mikaelbr** [comment]
@eiriksm er en del av core meetup og bartjs organizors og har tilgang til meetup.com event-registrering, @ev1stensberg, så mistenker at han kommer til å gjøre det. 👍 Dette kommer til å bli bra. Litt god js-sosialisering.

**Comment by eiriksm** [comment]
Jeg fikser en meetup jeg, poster link til "kladden" her så kan dere komme med innspill :)

**Comment by eiriksm** [comment]
Laget en kjapp "kladd" her: https://www.meetup.com/BartJS/events/232871690/

**Comment by mikaelbr** [comment]
Ser bra ut syns jeg. Vet ikke om @ev1stensberg har tilgang til å se det, men det er slik ut:

> Vi prøver oss på tidenes første BeerJS, Trondheim.
> 
> Agenda for kvelden er i utgangspunktet bare en uformell samling av folk som er interessert i JavaScript. En slags lodding av stemningen for denne typen arrangement, om du vil.
> 
> Om vi på sikt kan få BeerJS til å ha et litt mer faglig innhold, er det en hyggelig bieffekt. I første omgang ønsker vi alle velkommen til sosial samling der vi eventuelt kan mimre om vår første "undefined is not a function".
> 
> Liten påminnelse om BeerJS
> beer.js handler om å knytte bånd og å ha det sosialt for å styrke utviklersamfunn. Det er ikke påbudt å drikke på våre meetups.

@eiriksm Kanskje lenke til github-repoet?

**Comment by evenstensberg** [comment]
Har ikke tilgang til meetupen nei. Det er jo forsåvidt greit også, om du og Eirik har tilgang når jeg ikke er med på selve meetupen. Github repoet hadde vært greit å se though :)

**Comment by eiriksm** [comment]
Right, det tenkte jeg ikke på.

Oppdatert tekst, med lenke:

> Vi prøver oss på tidenes første BeerJS, Trondheim.
> 
> Agenda for kvelden er i utgangspunktet bare en uformell samling av folk som er interessert i JavaScript. En slags lodding av stemningen for denne typen arrangement, om du vil.
> 
> Om vi på sikt kan få BeerJS til å ha et litt mer faglig innhold, er det en hyggelig bieffekt. I første omgang ønsker vi alle velkommen til sosial samling der vi eventuelt kan mimre om vår første "undefined is not a function".
> 
> Liten påminnelse om BeerJS
> beer.js handler om å knytte bånd og å ha det sosialt for å styrke utviklersamfunn. Det er ikke påbudt å drikke på våre meetups.
> 
> For mer info, hvordan involvere seg og planlegging av fremtidige BeerJS, se https://github.com/BartJS/beerjs

**Comment by eiriksm** [comment]
Ålreit, lets do this :shipit:

https://www.meetup.com/BartJS/events/232871690/

**Comment by mikaelbr** [comment]
Jeg har alt markert "Se om det kommer noen" som done :P Nå er det 12 påmeldte, det kommer garantert noen av de. Erklærer det alt (kanskje prematurt) som en brakende suksess.

**Comment by evenstensberg** [comment]
Var det bra nok til et nytt arrangement eller hvordan var stemningen?

**Comment by mikaelbr** [comment]
Kommer nok til å måtte skje flere ganger. 👍

**Comment by evenstensberg** [comment]
sweet! Skal vi holde oss til omtrentlige datoer som vi har satt tidligere? annenhver uke, ish?
