### ISSUE TITLE
BeerJS #2

### ISSUE THREAD

**Issue by evenstensberg** [BartJS/beerjs#5]
Er det på tide med ny BeerJS? Fikk inntrykk av at alt gikk fint sist, og at det møtte opp mange. Vil takke @mikaelbr og @eiriksm for at de stiller opp og får dette til å gå rundt 🎆 

@eiriksm && @mikaelbr hva synes dere?

**Comment by eiriksm** [comment]
Absolutt. Nå er det jo den code in the dark om en ukes tid, så kanskje en uke eller 2 etter den? Personlig har jeg ferie (og er bortreist) i slutten av september, men er generelt positiv :)
